# Generated by Django 4.0 on 2022-04-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_userprofileinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-public_day',)},
        ),
    ]
